// src/components/theme-root/theme-root.tsx
import { Component, Host, h, Prop, Element } from '@stencil/core';
import { ColorArray } from './color-utils';
import { LCHPalette } from './lch-palette';

const rgb = (c: ColorArray) => c.map(x => Math.round(x)).join(',');

@Component({
  tag: 'theme-root',
  styleUrl: 'theme-root.scss',
})
export class ThemeRoot {
  @Prop() inline: boolean = false;
  @Prop() background: string = '#f2f2f2';
  @Prop() primary: string = '#22c646';
  @Prop() secondary: string | undefined = undefined;
  @Prop() tertiary: string | undefined = undefined;
  @Prop() error: string = '#ff0000';

  @Element() el?: HTMLElement;
  private waiting = false;

  componentWillRender() {
    this.el?.setAttribute('swap', '');
  }

  componentDidRender() {
    if (!this.waiting) {
      this.waiting = true;
      requestAnimationFrame(() => {
        this.waiting = false;
        this.el?.removeAttribute('swap');
      });
    }
  }

  render() {
    const neutralPal = LCHPalette.fromHex(this.background);
    const primaryPal = LCHPalette.fromHex(this.primary);
    const secondaryPal = this.secondary
      ? LCHPalette.fromHex(this.secondary)
      : new LCHPalette((primaryPal.hue + 60) % 360, primaryPal.chroma, primaryPal.initialLightness);
    const tertiaryPal = this.tertiary
      ? LCHPalette.fromHex(this.tertiary)
      : new LCHPalette(
          (primaryPal.hue + 180) % 360,
          primaryPal.chroma,
          primaryPal.initialLightness,
        );

    const primaryLightness = primaryPal.initialLightness!;
    const secondaryLightness = secondaryPal.initialLightness!;
    const tertiaryLightness = tertiaryPal.initialLightness!;

    const bgLightness = neutralPal.initialLightness!;

    return (
      <Host
        style={{
          '--bg': rgb(neutralPal.colorAt(bgLightness)),
          '--on-bg': rgb(neutralPal.colorOn(bgLightness)),
          '--pri': rgb(primaryPal.colorAt(primaryLightness)),
          '--on-pri': rgb(primaryPal.colorOn(primaryLightness)),
          '--on-bg-pri': rgb(primaryPal.colorOn(bgLightness)),
          '--sec': rgb(secondaryPal.colorAt(secondaryLightness)),
          '--on-sec': rgb(secondaryPal.colorOn(secondaryLightness)),
          '--on-bg-sec': rgb(secondaryPal.colorOn(bgLightness)),
          '--tri': rgb(tertiaryPal.colorAt(tertiaryLightness)),
          '--on-tri': rgb(tertiaryPal.colorOn(tertiaryLightness)),
          '--on-bg-tri': rgb(tertiaryPal.colorOn(bgLightness)),
        }}
      >
        <slot />
      </Host>
    );
  }
}

// src/lib/theme-root/ThemeRoot.svelte
<!-- 
  @component
  ThemeRoot allows you to change the page theme (background, foreground, accent, etc) for
  components. Theme values are all CSS variables, so you can embed multiple ThemeRoots
  in your application at once, and even nest them.

  ThemeRoot expects one child, which is automatically set to the full size of the parent, this is
  prefered over modifying the styles of this element itself. When placed in a flexbox, ThemeRoot
  expands to fill the space.
-->
<svelte:options immutable />

<script context="module" lang="ts">
	import './theme.scss';
	import { getContext, setContext } from 'svelte';
	import { writable } from 'svelte/store';
	import type { ColorArray } from './color-utils';
	import { LCHPalette } from './LCHPalette';

	const symbol = Symbol.for('@paperdave/ui/theme');

	export interface ThemeContext {
		neutral: LCHPalette;
		primary: LCHPalette;
		secondary: LCHPalette;
		tertiary: LCHPalette;
		// error: LCHPalette;
	}

	export function getTheme(): SvelteStore<ThemeContext> {
		return getContext(symbol);
	}
</script>

<script lang="ts">
	export let inline = false;

	export let background: string = '#f2f2f2';
	export let primary: string = '#22c646';
	export let secondary: string | undefined = undefined;
	export let tertiary: string | undefined = undefined;
	// export let error: string = '#ff0000';

	const rgb = (c: ColorArray) => c.map((x) => Math.round(x)).join(',');

	$: neutralPal = LCHPalette.fromHex(background);
	$: primaryPal = LCHPalette.fromHex(primary);
	$: secondaryPal = secondary
		? LCHPalette.fromHex(secondary)
		: new LCHPalette((primaryPal.hue + 60) % 360, primaryPal.chroma, primaryPal.initialLightness);
	$: tertiaryPal = tertiary
		? LCHPalette.fromHex(tertiary)
		: new LCHPalette((primaryPal.hue + 180) % 360, primaryPal.chroma, primaryPal.initialLightness);

	$: _primaryLightness = primaryPal.initialLightness!;
	$: _secondaryLightness = secondaryPal.initialLightness!;
	$: _tertiaryLightness = tertiaryPal.initialLightness!;

	$: bgLightness = neutralPal.initialLightness!;

	const themeContextStore = writable({} as ThemeContext);
	$: themeContextStore.set({
		neutral: neutralPal,
		primary: primaryPal,
		secondary: secondaryPal,
		tertiary: tertiaryPal
	});
	setContext(symbol, themeContextStore);

	let self: HTMLElement;
	$: typeof window !== 'undefined' && [neutralPal, primaryPal, secondaryPal, tertiaryPal] &&
		beforeSwapTheme();

	function beforeSwapTheme() {
		if (!self) return;
		self.classList.add('swap');
		setTimeout(() => {
			self.classList.remove('swap');
		});
	}
</script>

<theme-root
	bind:this={self}
	class:inline
	style:--bg={rgb(neutralPal.colorAt(bgLightness))}
	style:--on-bg={rgb(neutralPal.colorOn(bgLightness))}
	style:--pri={rgb(primaryPal.colorAt(_primaryLightness))}
	style:--on-pri={rgb(primaryPal.colorOn(_primaryLightness))}
	style:--on-bg-pri={rgb(
		primaryPal.colorAt((neutralPal.lightnessOn(bgLightness) + 1.5 * _primaryLightness) / 2.5)
	)}
	style:--sec={rgb(secondaryPal.colorAt(_secondaryLightness))}
	style:--on-sec={rgb(secondaryPal.colorOn(_secondaryLightness))}
	style:--on-bg-sec={rgb(
		secondaryPal.colorAt((neutralPal.lightnessOn(bgLightness) + 1.5 * _secondaryLightness) / 2.5)
	)}
	style:--tri={rgb(tertiaryPal.colorAt(_tertiaryLightness))}
	style:--on-tri={rgb(tertiaryPal.colorOn(_tertiaryLightness))}
	style:--on-bg-tri={rgb(
		tertiaryPal.colorAt((neutralPal.lightnessOn(bgLightness) + 1.5 * _tertiaryLightness) / 2.5)
	)}
>
	<slot />
</theme-root>
